[build]
  # custom build command that install bun and run build
  command = "build.sh"
  # vite output folder
  publish = ".vitepress/dist"

[build.environment]
   # disable NPM install
   NPM_FLAGS = "--version"